---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Service Catalog: S3 Reference Architecture: Public read-only bucket accessible from anywhere."

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: mah-buckt-pubra-whtx6
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"

Outputs:
  BucketName:
    Value:
      Ref: S3Bucket
    Description: Name of the Amazon S3 bucket.
  BucketARN:
    Value:
      Fn::GetAtt:
        - S3Bucket
        - Arn
    Description: ARN of the Amazon S3 bucket. 